name = "MyPkg15"
uuid = "b71a224a-0d1c-40c5-b3ff-15dd095c27c8"
authors = ["Shuhei Ohno"]
version = "0.0.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
julia = "1.11"
